name: bill_calculator_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1 # SDK Flutter của bạn

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  collection: ^1.18.0
  fl_chart: ^0.68.0
  uuid: ^4.4.0
  share_plus: ^11.0.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  #printing: ^5.12.0
  cached_network_image: ^3.3.1
  device_preview: ^1.1.0
  flutter_launcher_icons: ^0.14.3
  month_year_picker: ^0.5.0+1
  flutter_lints: ^6.0.0 # Thường ở dev_dependencies, nhưng nếu bạn muốn nó ở đây thì để nguyên
  flutter_native_splash: ^2.4.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  file_picker: ^10.2.0
  file_saver: ^0.2.14
  flutter_esc_pos_network: ^1.0.3 # Sử dụng phiên bản mới nhất
  esc_pos_utils_plus: ^2.0.4    # Sử dụng phiên bản mới nhất
    # Bluetooth Printing

  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_thermal_printer: ^1.2.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^6.0.0 # Nên để ở đây

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto.ttf
    - assets/nextbyte_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon_source.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4CAF50"

flutter_native_splash:
  color: "#ffffff"
  image: assets/nextbyte_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_12:
    image: assets/nextbyte_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/nextbyte_logo.png
    icon_background_color_dark: "#ffffff"
    branding: null